# Name classifies the name of the folder "./plugina/{name}"
name: LoopFreedomMod
# This classifies where the source files will be located
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
# This is the version, highly suggested not to be modified.
version: 6.2
# This is the description of your plugin
description: A Minecraft plugin created for FreedomOP
# Required software for pluin to function correctly.
softdepend: [BukkitTelnet, DisguiseCraft, WorldEdit, Essentials, BarAPI, Craftbukkit/Spigot]
# Devs/creators/coders
authors: [looperXD, Madgeek1450, DarthSalamon, buildcarter8, SupItsDillon, Robo_Lord, RobinGall2910, cowgomooo12, PieGuy7896, CrafterSmith12]
